import type { Metadata } from "next";
import { JetBrains_Mono, Matangi } from "next/font/google";
import "../ui/styles/globals.css";
import { cn } from "@/lib/utils";
import Header from "@/ui/components/Header";

const matangi = Matangi({
  subsets: ["latin"],
  variable: "--font-sans",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Cameron Stanley Web Development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        matangi.variable,
        jetbrainsMono.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <Header />
          <main>
            {children}
          </main>
      </body>
    </html>
  );
}
